<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiAdmin\Module' => __DIR__ . '/Module.php',
    'ZucchiAdmin\Controller\AbstractAdminController' => __DIR__ . '/src/ZucchiAdmin/Controller/AbstractAdminController.php',
    'ZucchiAdmin\Controller\DashboardController' => __DIR__ . '/src/ZucchiAdmin/Controller/DashboardController.php',
    'ZucchiAdmin\Event\AdminListener' => __DIR__ . '/src/ZucchiAdmin/Event/AdminListener.php',
    'ZucchiAdmin\Navigation\Service\AdminNavigationFactory' => __DIR__ . '/src/ZucchiAdmin/Navigation/Service/AdminNavigationFactory.php',
);