<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle($this->translate('Administration Panel'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?=$this->headLink()->appendStylesheet($this->basePath() . '/_css/zucchi/bootstrap/bootstrap.min.css')
                            ->appendStylesheet($this->basePath() . '/_css/zucchi/bootstrap/bootstrap-responsive.min.css')
                            ->appendStylesheet($this->basePath() . '/_css/zucchi/admin/style.css') ?>
        <?=$this->headScript()->appendFile($this->basePath() . '/_js/zucchi/admin/modernizr.min.js')
                              ->appendFile($this->basePath() . '/_js/zucchi/admin/jquery-1.8.0.min.js') 
                              ->appendFile($this->basePath() . '/_js/zucchi/bootstrap/bootstrap.min.js') ?>
    </head>
    <body>
<!-- <object id="svg" data="/_img/zucchi/admin/bokeh.svg" type="image/svg+xml"> -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <!-- Be sure to leave the brand out there if you want it shown -->
                    <a class="brand" href="#">Zucchi Admin</a>
                    
                    <?php echo $this->bootstrapNavbar('zucchiadmin.navigation'); ?>
                    
                    <!-- Everything you want hidden at 940px or less, place within here -->
                    <div class="nav-collapse">
                        <ul class="nav">
                        
                        </ul>
                        <!-- .nav, .navbar-search, .navbar-form, etc -->
                    </div>
                </div>
            </div>
        </div>
        <div id="admin">
            <div class="container">
                <?=$this->content?>
            </div>
        </div>
    
        <footer>
            <div class="container">
                <p>&copy; 2011- <?=date('Y')?> by Zucchi Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
        </footer>
    </body>
</html>
